---
version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
      - "9094:9094"
      - "9093:9093"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_EXTERNAL:PLAINTEXT, PLAINTEXT:PLAINTEXT, EXTERNAL_CLIENT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: DOCKER_EXTERNAL://broker:9094, PLAINTEXT://localhost:9092, EXTERNAL_CLIENT://192.168.0.11:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  nifi:
    image: apache/nifi
    hostname: nifi
    container_name: nifi
    depends_on: 
      - broker
    ports: 
      - 8000:8000
      - 8080:8080
    volumes:
      - $PWD/nifi-templates/:/opt/nifi/nifi-current/conf/templates
  crypto:
    image: crypto-pysim
    hostname: crypto
    container_name: crypto
    depends_on: 
      - broker
    ports: 
      - 5000:5000
  pyspark:
    image: jupyter/pyspark-notebook
    hostname: pyspark
    container_name: pyspark
    ports:
      - 8888:8888
    volumes:
     - $PWD/spark-notebooks/:/home/jovyan/
  cassandra:
    image: cassandra
    hostname: cassandra
    container_name: cassandra
    ports: 
      - 7000:7000
      - 9042:9042
    volumes: 
      - ~/cassandra_volume:/var/lib/cassandra
  frontend:
    image: frontend-crypto
    hostname: frontend
    container_name: frontend
    ports: 
      - 3000:3000
  backend:
    image: backend-crypto
    hostname: backend
    container_name: backend
    ports: 
      - 3001:3001


