apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: pyspark
  name: pyspark
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pyspark
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: pyspark
    spec:
      containers:
        - image: jupyter/pyspark-notebook
          name: pyspark
          ports:
            - containerPort: 8888
          resources: {}
      hostname: pyspark
      restartPolicy: Always
status: {}
